def human_rights_benchmark_score():
    dict = {'Adidas':23.0,
            'Tesco':21.5,
            'Marks&Spencer':20.5,
            'Fast Retailing':19.5,
            'Gap':18.5,
            'VF Corporation':20.5,
            'Burberry':17.5,
            'Inditex':17.5,
            'Puma':16.5,
            'Hennes & Mauritz':15.5,
            'Nike':15.5,
            'Under Armour':14.5,
            'Kering':14.0,
            'Aeon':13.5,
            'Wesfarmers':13.5,
            'Gildan Activewear':16.0,
            'Hanesbrands':13.0,
            'Next':13.0,
            'Nordstrom':11.5,
            'PVH Corporation':14.5,
            'Louis Vuitton':11.0,
            'Hermes International':9.5,
            'Walmart':9.5,
            'Hugo Boss':8.0,
            'Associated British Foods':7.5,
            'Amazon':6.0,
            'Ralph Lauren Corporation':6.0,
            'Skechers':6.0,
            'Costco':5.0,
            'Tapestry':5.0,
            'Prada':4.5,
            'Capri Holdings':4.0,
            'The TJX Companies':4.0,
            'Foot Locker':3.0,
            'ANTA Sports Products':2.5,
            'LPP':1.5}

    return dict


